# Generated by Django 3.1.7 on 2021-03-16 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0002_auto_20210315_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='wallet',
            field=models.DecimalField(blank=True, decimal_places=2, default=10000, max_digits=10, null=True),
        ),
    ]
