# Generated by Django 3.1.7 on 2021-03-17 12:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210315_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2021, 3, 17, 12, 19, 26, 77151, tzinfo=utc)),
        ),
    ]
