# Generated by Django 3.1.7 on 2021-03-23 19:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('shop', '0003_auto_20210317_1419'), ('shop', '0004_auto_20210317_1419'), ('shop', '0005_auto_20210317_1423')]

    dependencies = [
        ('shop', '0002_auto_20210315_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2021, 3, 17, 12, 19, 26, 77151, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='create_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='order',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2021, 3, 17, 12, 23, 1, 447328, tzinfo=utc)),
        ),
    ]
