# Generated by Django 3.1.7 on 2021-03-17 12:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20210317_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='create_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
