# Generated by Django 3.1.7 on 2021-03-17 12:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20210317_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2021, 3, 17, 12, 23, 1, 447328, tzinfo=utc)),
        ),
    ]
