# Generated by Django 3.1.7 on 2021-03-17 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20210317_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
