# Generated by Django 3.1.7 on 2021-03-23 18:45

from django.db import migrations


def space_troopers(apps, schema_editor):
    Product = apps.get_model('shop', 'Product')
    Product.objects.create(name="Space juggernaut", cost=20, amount=20)
    Product.objects.create(name="Space sniper", cost=30, amount=10)


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_product_photo'),
    ]

    operations = [
        migrations.RunPython(space_troopers, lambda x, y: None)
    ]
